SELECT LAGER.LAGER_ID as 'Lager ID',
    KOORDINATE.BREITENGRAD as 'Breitengrad',
    KOORDINATE.LAENGENGRAD as 'Laengengrad',
    LAGER.LAGERTYP as 'Lager Typ',
    COUNT(RESSOURCE_ID) as 'Anzahl Ressourcen'
FROM IST_GELAGERT_IN
    INNER JOIN LAGER ON LAGER.LAGER_ID = IST_GELAGERT_IN.LAGER_ID
    INNER JOIN KOORDINATE ON LAGER.KOORD_ID = KOORDINATE.ID
GROUP BY LAGER.LAGER_ID