SELECT
    a.BEREICH_ID,
    a.ABTEILUNG_NAME,
    a.TAETIGKEIT,
    m.MITARBEITER_ID AS LEITER_ID,
    b.VORNAME AS LEITER_VORNAME,
    b.NACHNAME AS LEITER_NACHNAME,
    m.LOGIN AS LEITER_LOGIN
FROM ABTEILUNG a
LEFT JOIN MITARBEITER m
    ON a.MITARBEITER_ID = m.MITARBEITER_ID
LEFT JOIN BEWOHNER b
    ON m.BEWOHNER_ID = b.BEWOHNER_ID
ORDER BY a.BEREICH_ID;
