SELECT 
    s.STADT_NAME,
    si.INVENTAR_ID,
    r.R_TYP AS RESSOURCEN_TYP,
    r.MENGE AS AKTUELLE_GESAMTMENGE,
    il.DATUM AS LOG_ZEITPUNKT
FROM STADT s
JOIN STADTINVENTAR si ON s.STADT_ID = si.STADT_ID
JOIN INVENTARLOG il ON si.INVENTAR_ID = il.INVENTAR_ID
JOIN RESSOURCE r ON il.RESSOURCE_ID = r.RESSOURCE_ID
ORDER BY il.DATUM DESC;