SELECT
    l.LAGER_ID,
    l.LAGERTYP,
    COUNT(r.RESSOURCE_ID) AS ANZAHL_RESSOURCEN,
    SUM(r.MENGE) AS GESAMTMENGE,
    SUM(r.GEWICHT) AS GESAMTGEWICHT,
    SUM(r.VOLUMEN) AS GESAMTVOLUMEN
FROM LAGER l
LEFT JOIN IST_GELAGERT_IN ig
    ON l.LAGER_ID = ig.LAGER_ID
LEFT JOIN RESSOURCE r
    ON ig.RESSOURCE_ID = r.RESSOURCE_ID
GROUP BY
    l.LAGER_ID,
    l.LAGERTYP
ORDER BY
    ANZAHL_RESSOURCEN DESC;
