DROP PROCEDURE IF EXISTS getRessourcenUeberschuss;
DELIMITER $$

CREATE PROCEDURE getRessourcenUeberschuss()
READS SQL DATA
BEGIN
SELECT
    bp2.RESSOURCE_ID,
    bp2.RESSOURCE_TYP,
    bp2.LAGER_ID,
    bp2.LAGERTYP,
    bp2.AKTUELLE_MENGE,
    bp2.MENGE_EINHEIT,
    bp2.MIN_SCHWELLENWERT,
    bp2.VERBRAUCH_PRO_SOL,
    bp2.SICHERHEITSPUFFER_7_SOL,
    bp2.MINDESTRESERVE,
    bp2.VERKAUFBARE_MENGE,
    ROUND((bp2.VERKAUFBARE_MENGE / NULLIF(bp2.AKTUELLE_MENGE, 0)) * 100, 2) AS VERKAUFBARE_MENGE_PROZENT,
    bp2.PRIORITAET,
    CASE
        WHEN bp2.PRIORITAET = 1 THEN 'NUR_NACH_FREIGABE'
        WHEN bp2.VERKAUFBARE_MENGE >= bp2.MINDESTRESERVE THEN 'DEUTLICHER_UEBERSCHUSS'
        ELSE 'MOEGLICHER_UEBERSCHUSS'
    END AS UEBERSCHUSS_STATUS,
    CASE
        WHEN bp2.PRIORITAET = 1 THEN 'KOLONIELEITUNG_PRUEFEN'
        ELSE 'VERKAUFSPOTENZIAL_BEWERTEN'
    END AS EMPFOHLENE_MASSNAHME
FROM (
    SELECT
        r.RESSOURCE_ID,
        r.R_TYP AS RESSOURCE_TYP,
        ig.LAGER_ID,
        l.LAGERTYP,
        COALESCE(r.MENGE, 0) AS AKTUELLE_MENGE,
        r.MENGE_EINHEIT,
        r.MIN_SCHWELLENWERT,
        r.VERBRAUCH_PRO_SOL,
        COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7 AS SICHERHEITSPUFFER_7_SOL,
        COALESCE(r.MIN_SCHWELLENWERT, 0) + (COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7) AS MINDESTRESERVE,
        GREATEST(
            COALESCE(r.MENGE, 0)
            - (COALESCE(r.MIN_SCHWELLENWERT, 0) + (COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7)),
            0
        ) AS VERKAUFBARE_MENGE,
        r.PRIORITAET,
        r.ABLAUFDATUM
    FROM RESSOURCE r
    INNER JOIN IST_GELAGERT_IN ig
        ON r.RESSOURCE_ID = ig.RESSOURCE_ID
    INNER JOIN LAGER l
        ON ig.LAGER_ID = l.LAGER_ID
    WHERE r.MIN_SCHWELLENWERT IS NOT NULL
) bp2
WHERE bp2.VERKAUFBARE_MENGE > 0
  AND (
      bp2.ABLAUFDATUM IS NULL
      OR DATE(bp2.ABLAUFDATUM) >= CURRENT_DATE
  )
ORDER BY
    CASE
        WHEN bp2.PRIORITAET = 1 THEN 1
        ELSE 0
    END ASC,
    bp2.VERKAUFBARE_MENGE DESC,
    bp2.RESSOURCE_TYP ASC;
END $$

DELIMITER ;
