DROP PROCEDURE IF EXISTS getRessourcenWithLager;
DELIMITER $$

CREATE PROCEDURE getRessourcenWithLager()
READS SQL DATA
BEGIN
SELECT
    ig.LAGER_ID,
    r.R_TYP,
    r.MENGE,
    r.MENGE_EINHEIT
FROM IST_GELAGERT_IN ig
INNER JOIN RESSOURCE r
    ON ig.RESSOURCE_ID = r.RESSOURCE_ID
ORDER BY ig.LAGER_ID;
END $$

DELIMITER ;
