SELECT
    rv.VERKAUF_ID,
    rv.STATUS AS VERKAUF_STATUS,
    rv.ERSTELLT_AM,
    rv.WAEHRUNG,
    rv.GESAMTWERT,
    eu.UNTERNEHMEN_ID,
    eu.NAME AS UNTERNEHMEN_NAME,
    eu.BRANCHE,
    eu.KONTAKT_NAME,
    eu.KONTAKT_EMAIL,
    rvp.VERKAUF_POSITION_ID,
    rvp.RESSOURCE_ID,
    r.R_TYP AS RESSOURCE_TYP,
    rvp.LAGER_ID,
    l.LAGERTYP,
    rvp.MENGE AS ABGABE_MENGE,
    rvp.EINHEIT,
    rvp.EINZELPREIS,
    rvp.POSITIONSWERT,
    rub.BEWERTUNG_ID,
    rub.VERKAUFBARE_MENGE AS FREIGEGEBENE_MENGE,
    rub.STATUS AS BEWERTUNGSSTATUS,
    CASE
        WHEN LOWER(COALESCE(rv.STATUS, '')) IN ('vorbereitet', 'freigegeben')
            AND rvp.MENGE <= COALESCE(rub.VERKAUFBARE_MENGE, rvp.MENGE)
            THEN 'ABGABE_FACHLICH_VORBEREITET'
        WHEN rvp.MENGE > COALESCE(rub.VERKAUFBARE_MENGE, 0)
            THEN 'MENGE_PRUEFEN'
        ELSE 'STATUS_PRUEFEN'
    END AS ABGABE_STATUS,
    rv.BEMERKUNG
FROM RESSOURCEN_VERKAUF rv
INNER JOIN EXTERNES_UNTERNEHMEN eu
    ON rv.UNTERNEHMEN_ID = eu.UNTERNEHMEN_ID
INNER JOIN RESSOURCEN_VERKAUF_POSITION rvp
    ON rv.VERKAUF_ID = rvp.VERKAUF_ID
INNER JOIN RESSOURCE r
    ON rvp.RESSOURCE_ID = r.RESSOURCE_ID
INNER JOIN LAGER l
    ON rvp.LAGER_ID = l.LAGER_ID
LEFT JOIN RESSOURCEN_UEBERSCHUSS_BEWERTUNG rub
    ON rvp.BEWERTUNG_ID = rub.BEWERTUNG_ID
ORDER BY
    rv.ERSTELLT_AM DESC,
    rv.VERKAUF_ID ASC,
    rvp.VERKAUF_POSITION_ID ASC;
