SELECT
    bp2.RESSOURCE_ID,
    bp2.RESSOURCE_TYP,
    bp2.LAGER_ID,
    bp2.LAGERTYP,
    bp2.AKTUELLE_MENGE,
    bp2.MENGE_EINHEIT,
    bp2.MINDESTRESERVE,
    bp2.VERKAUFBARE_MENGE,
    bp2.PRIORITAET,
    rub.BEWERTUNG_ID,
    rub.BEWERTUNGSDATUM,
    rub.STATUS AS BEWERTUNGSSTATUS,
    rub.BEGRUENDUNG,
    CASE
        WHEN LOWER(COALESCE(rub.STATUS, '')) = 'freigegeben' THEN 'BEREITS_FREIGEGEBEN'
        WHEN bp2.PRIORITAET = 1 THEN 'KRITISCH_PRUEFEN'
        WHEN bp2.VERKAUFBARE_MENGE >= bp2.MINDESTRESERVE THEN 'HOHES_VERKAUFSPOTENZIAL'
        ELSE 'MITTLERES_VERKAUFSPOTENZIAL'
    END AS VERKAUFSPOTENZIAL_STATUS,
    CASE
        WHEN LOWER(COALESCE(rub.STATUS, '')) = 'freigegeben' THEN 'EXTERNE_ABGABE_VORBEREITEN'
        WHEN bp2.PRIORITAET = 1 THEN 'FREIGABE_DURCH_KOLONIELEITUNG_EINHOLEN'
        ELSE 'UEBERSCHUSSBEWERTUNG_ANLEGEN'
    END AS EMPFOHLENE_MASSNAHME
FROM (
    SELECT
        r.RESSOURCE_ID,
        r.R_TYP AS RESSOURCE_TYP,
        ig.LAGER_ID,
        l.LAGERTYP,
        COALESCE(r.MENGE, 0) AS AKTUELLE_MENGE,
        r.MENGE_EINHEIT,
        COALESCE(r.MIN_SCHWELLENWERT, 0) + (COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7) AS MINDESTRESERVE,
        GREATEST(
            COALESCE(r.MENGE, 0)
            - (COALESCE(r.MIN_SCHWELLENWERT, 0) + (COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7)),
            0
        ) AS VERKAUFBARE_MENGE,
        r.PRIORITAET,
        r.ABLAUFDATUM
    FROM RESSOURCE r
    INNER JOIN IST_GELAGERT_IN ig
        ON r.RESSOURCE_ID = ig.RESSOURCE_ID
    INNER JOIN LAGER l
        ON ig.LAGER_ID = l.LAGER_ID
    WHERE r.MIN_SCHWELLENWERT IS NOT NULL
) bp2
LEFT JOIN RESSOURCEN_UEBERSCHUSS_BEWERTUNG rub
    ON bp2.RESSOURCE_ID = rub.RESSOURCE_ID
   AND bp2.LAGER_ID = rub.LAGER_ID
WHERE bp2.VERKAUFBARE_MENGE > 0
  AND (
      bp2.ABLAUFDATUM IS NULL
      OR DATE(bp2.ABLAUFDATUM) >= CURRENT_DATE
  )
ORDER BY
    CASE
        WHEN LOWER(COALESCE(rub.STATUS, '')) = 'freigegeben' THEN 0
        WHEN bp2.PRIORITAET = 1 THEN 2
        ELSE 1
    END ASC,
    bp2.VERKAUFBARE_MENGE DESC,
    bp2.RESSOURCE_TYP ASC;
