DROP PROCEDURE IF EXISTS getAllCitizens;
DELIMITER $$

CREATE PROCEDURE getAllCitizens()
READS SQL DATA
BEGIN
SELECT
    b.BEWOHNER_ID,
    b.VORNAME,
    b.NACHNAME,
    CONCAT(a.STRA_E, ' ', a.HAUSNUMMER, ', ', s.STADT_NAME) AS adresse,
    CASE
        WHEN m.BEWOHNER_ID IS NOT NULL THEN 'Ja'
        ELSE 'Nein'
    END AS ist_mitarbeiter
FROM BEWOHNER b
LEFT JOIN MITARBEITER m
    ON b.BEWOHNER_ID = m.BEWOHNER_ID
INNER JOIN ADRESSE a
    ON b.ADRESSE_ID = a.ADRESSE_ID
INNER JOIN STADT s
    ON a.STADT_ID = s.STADT_ID;
END $$

DELIMITER ;
