DROP PROCEDURE IF EXISTS getAllLager;
DELIMITER $$

CREATE PROCEDURE getAllLager()
READS SQL DATA
BEGIN
SELECT
    l.LAGER_ID AS `Lager ID`,
    k.BREITENGRAD AS `Breitengrad`,
    k.LAENGENGRAD AS `Laengengrad`,
    l.LAGERTYP AS `Lager Typ`,
    COUNT(ig.RESSOURCE_ID) AS `Anzahl Ressourcen`
FROM LAGER l
INNER JOIN KOORDINATE k
    ON l.KOORD_ID = k.ID
LEFT JOIN IST_GELAGERT_IN ig
    ON l.LAGER_ID = ig.LAGER_ID
GROUP BY
    l.LAGER_ID,
    k.BREITENGRAD,
    k.LAENGENGRAD,
    l.LAGERTYP
ORDER BY l.LAGER_ID;
END $$

DELIMITER ;
