DROP PROCEDURE IF EXISTS getAllEmployees;
DELIMITER $$

CREATE PROCEDURE getAllEmployees()
READS SQL DATA
BEGIN
SELECT
    m.LOGIN,
    b.VORNAME,
    b.NACHNAME,
    m.GEHALT
FROM MITARBEITER m
INNER JOIN BEWOHNER b
    ON m.BEWOHNER_ID = b.BEWOHNER_ID;
END $$

DELIMITER ;
