DROP PROCEDURE IF EXISTS getCurrentBithday;
DELIMITER $$

CREATE PROCEDURE getCurrentBithday()
READS SQL DATA
BEGIN
SELECT
    b.BEWOHNER_ID,
    b.VORNAME,
    b.NACHNAME,
    b.GEB
FROM BEWOHNER b
WHERE MONTH(b.GEB) = MONTH(CURRENT_DATE)
  AND DAY(b.GEB) = DAY(CURRENT_DATE);
END $$

DELIMITER ;
