DROP PROCEDURE IF EXISTS getCitiesWithoutTransportConnection;
DELIMITER $$

CREATE PROCEDURE getCitiesWithoutTransportConnection()
READS SQL DATA
BEGIN
SELECT s.STADT_NAME
FROM STADT s
LEFT JOIN TRANSPORTWEGE t
    ON s.STADT_ID = t.STADT_ID
WHERE t.TPW_ID IS NULL
ORDER BY s.STADT_NAME;
END $$

DELIMITER ;
