DROP PROCEDURE IF EXISTS getCitizensCount;
DELIMITER $$

CREATE PROCEDURE getCitizensCount()
READS SQL DATA
BEGIN
SELECT
    COUNT(*) AS citizens_count,
    COALESCE(SUM(CASE
        WHEN GEB <= CURRENT_DATE AND GEB > DATE_SUB(CURRENT_DATE, INTERVAL 18 YEAR) THEN 1
        ELSE 0
    END), 0) AS minors_count
FROM BEWOHNER;
END $$

DELIMITER ;
