DROP PROCEDURE IF EXISTS getCitiesWithoutEnergySource;
DELIMITER $$

CREATE PROCEDURE getCitiesWithoutEnergySource()
READS SQL DATA
BEGIN
SELECT
    s.STADT_ID,
    s.STADT_NAME
FROM STADT s
LEFT JOIN VERSORGT_STADT vs
    ON s.STADT_ID = vs.STADT_ID
WHERE vs.EQ_ID IS NULL
ORDER BY s.STADT_NAME;
END $$

DELIMITER ;
