DROP PROCEDURE IF EXISTS getCurrentEnergieLeistung;
DELIMITER $$

CREATE PROCEDURE getCurrentEnergieLeistung()
READS SQL DATA
BEGIN
SELECT COALESCE(SUM(AKTUELLE_LEISTUNG), 0) AS current_energy_power
FROM ENERGIEQUELLE;
END $$

DELIMITER ;
