DROP PROCEDURE IF EXISTS getDepartmentResourceDependencies;
DELIMITER $$

CREATE PROCEDURE getDepartmentResourceDependencies()
READS SQL DATA
BEGIN
SELECT
    a.BEREICH_ID,
    a.ABTEILUNG_NAME,
    r.RESSOURCE_ID,
    r.R_TYP,
    r.PRIORITAET
FROM BAUT_AB ba
INNER JOIN ABTEILUNG a
    ON ba.BEREICH_ID = a.BEREICH_ID
INNER JOIN RESSOURCE r
    ON ba.RESSOURCE_ID = r.RESSOURCE_ID
ORDER BY
    a.ABTEILUNG_NAME,
    r.PRIORITAET,
    r.R_TYP;
END $$

DELIMITER ;
