DROP PROCEDURE IF EXISTS getEnergySourcesByCity;
DELIMITER $$

CREATE PROCEDURE getEnergySourcesByCity()
READS SQL DATA
BEGIN
SELECT
    s.STADT_ID,
    s.STADT_NAME,
    e.EQ_ID,
    e.EQ_TYP,
    e.AKTUELLE_LEISTUNG,
    e.KAPAZITAET_MAX
FROM VERSORGT_STADT vs
INNER JOIN STADT s
    ON vs.STADT_ID = s.STADT_ID
INNER JOIN ENERGIEQUELLE e
    ON vs.EQ_ID = e.EQ_ID
ORDER BY
    s.STADT_NAME,
    e.EQ_ID;
END $$

DELIMITER ;
