DROP PROCEDURE IF EXISTS getFlotte;
DELIMITER $$

CREATE PROCEDURE getFlotte()
READS SQL DATA
BEGIN
SELECT
    'Boden' AS TYP,
    F_NAME AS NAME,
    F_STATUS AS STATUS,
    NULL AS IMG
FROM FAHRZEUGE
UNION ALL
SELECT
    'Raum' AS TYP,
    RF_TYP AS NAME,
    RF_STATUS AS STATUS,
    NULL AS IMG
FROM RAUMFAHRZEUG;
END $$

DELIMITER ;
