DROP PROCEDURE IF EXISTS getLagerVersorgungAtRisk;
DELIMITER $$

CREATE PROCEDURE getLagerVersorgungAtRisk()
READS SQL DATA
BEGIN
SELECT
    LAGER_ID,
    COALESCE(AKTUELLE_LEISTUNG, 0) AS aktuelle_leistung,
    KAPAZITAET_MAX
FROM ENERGIEQUELLE
WHERE KAPAZITAET_MAX IS NOT NULL
  AND KAPAZITAET_MAX > 0
  AND COALESCE(AKTUELLE_LEISTUNG, 0) / KAPAZITAET_MAX < 0.5;
END $$

DELIMITER ;
