DROP PROCEDURE IF EXISTS getLowTreibstoff;
DELIMITER $$

CREATE PROCEDURE getLowTreibstoff()
READS SQL DATA
BEGIN
SELECT
    RF_TYP,
    TREIBSTOFF_STAND
FROM RAUMFAHRZEUG
WHERE TREIBSTOFF_STAND < 45.0
ORDER BY TREIBSTOFF_STAND ASC;
END $$

DELIMITER ;
