DROP PROCEDURE IF EXISTS getRessourcesAtRisk;
DELIMITER $$

CREATE PROCEDURE getRessourcesAtRisk()
READS SQL DATA
BEGIN
SELECT
    r.RESSOURCE_ID,
    r.R_TYP AS ressource_typ,
    r.ABLAUFDATUM,
    ig.LAGER_ID
FROM RESSOURCE r
INNER JOIN IST_GELAGERT_IN ig
    ON r.RESSOURCE_ID = ig.RESSOURCE_ID
WHERE r.ABLAUFDATUM BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY)
ORDER BY r.ABLAUFDATUM ASC;
END $$

DELIMITER ;
