DROP PROCEDURE IF EXISTS getRessourcesBelowMin;
DELIMITER $$

CREATE PROCEDURE getRessourcesBelowMin()
READS SQL DATA
BEGIN
SELECT
    r.RESSOURCE_ID,
    r.R_TYP,
    r.MENGE,
    r.MIN_SCHWELLENWERT,
    l.LAGERTYP
FROM RESSOURCE r
INNER JOIN IST_GELAGERT_IN ig
    ON r.RESSOURCE_ID = ig.RESSOURCE_ID
INNER JOIN LAGER l
    ON ig.LAGER_ID = l.LAGER_ID
WHERE r.MENGE < r.MIN_SCHWELLENWERT;
END $$

DELIMITER ;
