DROP PROCEDURE IF EXISTS getResidentCountByAddress;
DELIMITER $$

CREATE PROCEDURE getResidentCountByAddress()
READS SQL DATA
BEGIN
SELECT
    a.ADRESSE_ID,
    CONCAT(a.STRA_E, ' ', a.HAUSNUMMER) AS ADRESSE,
    s.STADT_NAME,
    COUNT(b.BEWOHNER_ID) AS ANZAHL_BEWOHNER
FROM ADRESSE a
INNER JOIN STADT s
    ON a.STADT_ID = s.STADT_ID
LEFT JOIN BEWOHNER b
    ON a.ADRESSE_ID = b.ADRESSE_ID
GROUP BY
    a.ADRESSE_ID,
    a.STRA_E,
    a.HAUSNUMMER,
    s.STADT_NAME
ORDER BY ANZAHL_BEWOHNER DESC;
END $$

DELIMITER ;
