DROP PROCEDURE IF EXISTS getRessourceLog;
DELIMITER $$

CREATE PROCEDURE getRessourceLog()
READS SQL DATA
BEGIN
SELECT
    s.STADT_NAME,
    si.INVENTAR_ID,
    r.R_TYP AS RESSOURCEN_TYP,
    r.MENGE AS AKTUELLE_GESAMTMENGE,
    il.DATUM AS LOG_ZEITPUNKT
FROM STADT s
INNER JOIN STADTINVENTAR si
    ON s.STADT_ID = si.STADT_ID
INNER JOIN INVENTARLOG il
    ON si.INVENTAR_ID = il.INVENTAR_ID
INNER JOIN RESSOURCE r
    ON il.RESSOURCE_ID = r.RESSOURCE_ID
ORDER BY il.DATUM DESC;
END $$

DELIMITER ;
