DROP PROCEDURE IF EXISTS getStorageResourceSummary;
DELIMITER $$

CREATE PROCEDURE getStorageResourceSummary()
READS SQL DATA
BEGIN
SELECT
    l.LAGER_ID,
    l.LAGERTYP,
    COUNT(r.RESSOURCE_ID) AS ANZAHL_RESSOURCEN,
    COALESCE(SUM(r.MENGE), 0) AS GESAMTMENGE,
    COALESCE(SUM(r.GEWICHT), 0) AS GESAMTGEWICHT,
    COALESCE(SUM(r.VOLUMEN), 0) AS GESAMTVOLUMEN
FROM LAGER l
LEFT JOIN IST_GELAGERT_IN ig
    ON l.LAGER_ID = ig.LAGER_ID
LEFT JOIN RESSOURCE r
    ON ig.RESSOURCE_ID = r.RESSOURCE_ID
GROUP BY
    l.LAGER_ID,
    l.LAGERTYP
ORDER BY ANZAHL_RESSOURCEN DESC;
END $$

DELIMITER ;
