SELECT
    DATE(b.DATUM) AS datum,
    r.R_TYP AS ressource,
    COALESCE(r.MENGE_EINHEIT, '') AS einheit,
    ROUND(SUM(b.MENGE), 2) AS verbrauch
FROM BESTANDSBEWEGUNG b
INNER JOIN RESSOURCE r
    ON r.RESSOURCE_ID = b.RESSOURCE_ID
WHERE b.BEWEGUNGSART = 'VERBRAUCH'
  AND r.R_TYP IN ('Wasser', 'Sauerstoff', 'Nahrung')
  AND b.DATUM >= DATE_SUB(
      CAST(DATE_FORMAT(CURRENT_DATE, '%Y-%m-01') AS DATE),
      INTERVAL 11 MONTH
  )
  AND b.DATUM < DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY)
GROUP BY
    DATE(b.DATUM),
    r.RESSOURCE_ID,
    r.R_TYP,
    r.MENGE_EINHEIT
ORDER BY
    DATE(b.DATUM),
    r.R_TYP;
