SELECT
    r.RESSOURCE_ID,
    r.R_TYP AS RESSOURCE_TYP,
    COALESCE(r.MENGE, 0) AS AKTUELLE_MENGE,
    r.MENGE_EINHEIT,
    r.MIN_SCHWELLENWERT,
    GREATEST(r.MIN_SCHWELLENWERT - COALESCE(r.MENGE, 0), 0) AS FEHLMENGE,
    ROUND(
        (GREATEST(r.MIN_SCHWELLENWERT - COALESCE(r.MENGE, 0), 0) / NULLIF(r.MIN_SCHWELLENWERT, 0)) * 100,
        2
    ) AS FEHLMENGE_PROZENT,
    r.PRIORITAET,
    ig.LAGER_ID,
    l.LAGERTYP,
    CASE
        WHEN r.PRIORITAET = 1
            OR GREATEST(r.MIN_SCHWELLENWERT - COALESCE(r.MENGE, 0), 0) >= (r.MIN_SCHWELLENWERT * 0.5)
            THEN 'SOFORT_PRUEFEN'
        WHEN r.PRIORITAET = 2
            THEN 'HOCH'
        ELSE 'MITTEL'
    END AS HANDLUNGSPRIORITAET,
    'UNTER_MINDESTBESTAND' AS STATUS
FROM RESSOURCE r
LEFT JOIN IST_GELAGERT_IN ig
    ON r.RESSOURCE_ID = ig.RESSOURCE_ID
LEFT JOIN LAGER l
    ON ig.LAGER_ID = l.LAGER_ID
WHERE r.MIN_SCHWELLENWERT IS NOT NULL
  AND COALESCE(r.MENGE, 0) < r.MIN_SCHWELLENWERT
ORDER BY
    CASE
        WHEN r.PRIORITAET IS NULL THEN 99
        ELSE r.PRIORITAET
    END ASC,
    FEHLMENGE DESC,
    r.R_TYP ASC;
