DROP PROCEDURE IF EXISTS getNachschubanforderungen;
DELIMITER $$

CREATE PROCEDURE getNachschubanforderungen()
READS SQL DATA
BEGIN
SELECT
    bp1.NACHSCHUBANFORDERUNG_ID,
    bp1.RESSOURCE_ID,
    bp1.RESSOURCE_TYP,
    bp1.LAGER_ID,
    bp1.LAGERTYP,
    bp1.AKTUELLE_MENGE,
    bp1.MENGE_EINHEIT,
    bp1.MIN_SCHWELLENWERT,
    bp1.VERBRAUCH_PRO_SOL,
    bp1.SICHERHEITSPUFFER_7_SOL,
    bp1.ANFORDERUNGSMENGE,
    bp1.INTERN_VERFUEGBARE_MENGE,
    CASE
        WHEN bp1.IST_ABGELAUFEN = 1 AND bp1.IST_UNTER_MINDESTBESTAND = 1
            THEN 'ABGELAUFEN_UND_UNTER_MINDESTBESTAND'
        WHEN bp1.IST_ABGELAUFEN = 1
            THEN 'ABGELAUFENER_BESTAND_ERSETZEN'
        ELSE 'UNTER_MINDESTBESTAND'
    END AS ANFORDERUNGSGRUND,
    CASE
        WHEN bp1.PRIORITAET = 1
            OR bp1.IST_ABGELAUFEN = 1
            OR bp1.INTERN_VERFUEGBARE_MENGE < bp1.ANFORDERUNGSMENGE
            THEN 'HOCH'
        WHEN bp1.PRIORITAET = 2
            THEN 'MITTEL'
        ELSE 'NIEDRIG'
    END AS ANFORDERUNGSPRIORITAET,
    CASE
        WHEN bp1.IST_ABGELAUFEN = 1
            THEN 'BESTAND_SPERREN_UND_ERSATZ_BESCHAFFEN'
        WHEN bp1.INTERN_VERFUEGBARE_MENGE >= bp1.ANFORDERUNGSMENGE
            THEN 'INTERNE_UMLAGERUNG_PRUEFEN'
        ELSE 'EXTERNEN_NACHSCHUB_ANFORDERN'
    END AS EMPFOHLENE_MASSNAHME
FROM (
    SELECT
        CONCAT('NA-', LPAD(CAST(r.RESSOURCE_ID AS UNSIGNED), 4, '0'), '-', DATE_FORMAT(CURRENT_DATE, '%Y%m%d')) AS NACHSCHUBANFORDERUNG_ID,
        r.RESSOURCE_ID,
        r.R_TYP AS RESSOURCE_TYP,
        ig.LAGER_ID,
        l.LAGERTYP,
        COALESCE(r.MENGE, 0) AS AKTUELLE_MENGE,
        r.MENGE_EINHEIT,
        r.MIN_SCHWELLENWERT,
        r.VERBRAUCH_PRO_SOL,
        COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7 AS SICHERHEITSPUFFER_7_SOL,
        r.PRIORITAET,
        CASE
            WHEN r.MIN_SCHWELLENWERT IS NOT NULL
                AND COALESCE(r.MENGE, 0) < r.MIN_SCHWELLENWERT
                THEN 1
            ELSE 0
        END AS IST_UNTER_MINDESTBESTAND,
        CASE
            WHEN r.ABLAUFDATUM IS NOT NULL
                AND DATE(r.ABLAUFDATUM) < CURRENT_DATE
                THEN 1
            ELSE 0
        END AS IST_ABGELAUFEN,
        CASE
            WHEN r.ABLAUFDATUM IS NOT NULL
                AND DATE(r.ABLAUFDATUM) < CURRENT_DATE
                THEN GREATEST(COALESCE(r.MIN_SCHWELLENWERT, 0), COALESCE(r.MENGE, 0))
            WHEN r.MIN_SCHWELLENWERT IS NOT NULL
                AND COALESCE(r.MENGE, 0) < r.MIN_SCHWELLENWERT
                THEN GREATEST(r.MIN_SCHWELLENWERT - COALESCE(r.MENGE, 0), 0) + (COALESCE(r.VERBRAUCH_PRO_SOL, 0) * 7)
            ELSE 0
        END AS ANFORDERUNGSMENGE,
        GREATEST(
            COALESCE(rt.NUTZBARE_GESAMTMENGE, 0)
            - CASE
                WHEN r.ABLAUFDATUM IS NOT NULL
                    AND DATE(r.ABLAUFDATUM) < CURRENT_DATE
                    THEN 0
                ELSE COALESCE(r.MENGE, 0)
            END,
            0
        ) AS INTERN_VERFUEGBARE_MENGE
    FROM RESSOURCE r
    LEFT JOIN IST_GELAGERT_IN ig
        ON r.RESSOURCE_ID = ig.RESSOURCE_ID
    LEFT JOIN LAGER l
        ON ig.LAGER_ID = l.LAGER_ID
    LEFT JOIN (
        SELECT
            R_TYP,
            SUM(
                CASE
                    WHEN ABLAUFDATUM IS NULL
                        OR DATE(ABLAUFDATUM) >= CURRENT_DATE
                        THEN COALESCE(MENGE, 0)
                    ELSE 0
                END
            ) AS NUTZBARE_GESAMTMENGE
        FROM RESSOURCE
        GROUP BY R_TYP
    ) rt
        ON rt.R_TYP = r.R_TYP
    WHERE (
        r.MIN_SCHWELLENWERT IS NOT NULL
        AND COALESCE(r.MENGE, 0) < r.MIN_SCHWELLENWERT
    )
    OR (
        r.ABLAUFDATUM IS NOT NULL
        AND DATE(r.ABLAUFDATUM) < CURRENT_DATE
    )
) bp1
WHERE bp1.ANFORDERUNGSMENGE > 0
ORDER BY
    CASE
        WHEN bp1.IST_ABGELAUFEN = 1 THEN 0
        WHEN bp1.PRIORITAET = 1 THEN 1
        ELSE 2
    END ASC,
    bp1.ANFORDERUNGSMENGE DESC,
    bp1.RESSOURCE_TYP ASC;
END $$

DELIMITER ;
