DROP PROCEDURE IF EXISTS getRessourcesAtRisk;
DELIMITER $$

CREATE PROCEDURE getRessourcesAtRisk()
READS SQL DATA
BEGIN
SELECT
    r.RESSOURCE_ID,
    r.R_TYP AS RESSOURCE_TYP,
    COALESCE(r.MENGE, 0) AS AKTUELLE_MENGE,
    r.MENGE_EINHEIT,
    r.ABLAUFDATUM,
    DATEDIFF(DATE(r.ABLAUFDATUM), CURRENT_DATE) AS TAGE_BIS_ABLAUF,
    r.PRIORITAET,
    ig.LAGER_ID,
    l.LAGERTYP,
    CASE
        WHEN DATE(r.ABLAUFDATUM) < CURRENT_DATE THEN 'ABGELAUFEN'
        WHEN DATE(r.ABLAUFDATUM) = CURRENT_DATE THEN 'LAEUFT_HEUTE_AB'
        WHEN DATEDIFF(DATE(r.ABLAUFDATUM), CURRENT_DATE) <= 7 THEN 'LAEUFT_IN_7_TAGEN_AB'
        ELSE 'LAEUFT_IN_30_TAGEN_AB'
    END AS RISIKOSTATUS,
    CASE
        WHEN DATE(r.ABLAUFDATUM) < CURRENT_DATE THEN 'BESTAND_SPERREN_UND_ERSATZ_PRUEFEN'
        WHEN r.PRIORITAET = 1
            OR DATEDIFF(DATE(r.ABLAUFDATUM), CURRENT_DATE) <= 7
            THEN 'BEVORZUGT_VERBRAUCHEN_ODER_ERSETZEN'
        ELSE 'FEFO_VERBRAUCH_PLANEN'
    END AS EMPFOHLENE_MASSNAHME
FROM RESSOURCE r
LEFT JOIN IST_GELAGERT_IN ig
    ON r.RESSOURCE_ID = ig.RESSOURCE_ID
LEFT JOIN LAGER l
    ON ig.LAGER_ID = l.LAGER_ID
WHERE r.ABLAUFDATUM IS NOT NULL
  AND DATE(r.ABLAUFDATUM) <= DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY)
ORDER BY
    CASE
        WHEN DATE(r.ABLAUFDATUM) < CURRENT_DATE THEN 0
        ELSE 1
    END ASC,
    r.ABLAUFDATUM ASC,
    CASE
        WHEN r.PRIORITAET IS NULL THEN 99
        ELSE r.PRIORITAET
    END ASC,
    r.R_TYP ASC;
END $$

DELIMITER ;
