DROP PROCEDURE IF EXISTS getCitiesWithKoords;
DELIMITER $$

CREATE PROCEDURE getCitiesWithKoords()
READS SQL DATA
BEGIN
SELECT
    s.STADT_NAME,
    k.BREITENGRAD,
    k.LAENGENGRAD
FROM STADT s
INNER JOIN KOORDINATE k
    ON s.KOORD_ID = k.ID
ORDER BY s.STADT_NAME;
END $$

DELIMITER ;
