DROP PROCEDURE IF EXISTS getEmployeeCountByDepartment;
DELIMITER $$

CREATE PROCEDURE getEmployeeCountByDepartment()
READS SQL DATA
BEGIN
SELECT
    a.BEREICH_ID,
    a.ABTEILUNG_NAME,
    COUNT(m.MITARBEITER_ID) AS ANZAHL_MITARBEITER
FROM ABTEILUNG a
LEFT JOIN MITARBEITER m
    ON a.BEREICH_ID = m.ABT_BEREICH_ID
GROUP BY
    a.BEREICH_ID,
    a.ABTEILUNG_NAME
ORDER BY ANZAHL_MITARBEITER DESC;
END $$

DELIMITER ;
