SELECT
    a.BEREICH_ID,
    a.ABTEILUNG_NAME,
    COUNT(m.MITARBEITER_ID) AS ANZAHL_MITARBEITER
FROM ABTEILUNG a
LEFT JOIN MITARBEITER m
    ON a.BEREICH_ID = m.ABT_BEREICH_ID
GROUP BY
    a.BEREICH_ID,
    a.ABTEILUNG_NAME
ORDER BY
    ANZAHL_MITARBEITER DESC;
